### ISSUE TITLE
Is the dev set necessary?

### ISSUE THREAD

**Issue by fpcsong** [smartyfh/DST-MetaASSIST#1]
Thanks for your nice work!

I have a question, why not just sample another minibatch from the train set in Algorithm 1(line 11)?

**Comment by smartyfh** [comment]
> 



> Thanks for your nice work!
> 
> I have a question, why not just sample another minibatch from the train set in Algorithm 1(line 11)?

Hi, thank you for the question.

there are two reasons: 1) the training set is noisy while the dev set is almost clean; 2) the idea is that the best model should achieve the best performance on the dev set, the same as how we usually select the best checkpoint when training ML models.
